### ISSUE TITLE
Master is initializing

### ISSUE THREAD

**Issue by vonkonyoung** [vonkonyoung/myhbase#1]
hbase创建表的时候，报的这个错误：
hbase(main):017:0> create 'Student','baseInfo','schoolInfo'

ERROR: org.apache.hadoop.hbase.PleaseHoldException: Master is initializing
	at org.apache.hadoop.hbase.master.HMaster.checkInitialized(HMaster.java:2977)
	at org.apache.hadoop.hbase.master.HMaster.createTable(HMaster.java:1944)
	at org.apache.hadoop.hbase.master.MasterRpcServices.createTable(MasterRpcServices.java:603)
	at org.apache.hadoop.hbase.shaded.protobuf.generated.MasterProtos$MasterService$2.callBlockingMethod(MasterProtos.java)
	at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:413)
	at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:130)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:324)
	at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:304)

Creates a table. Pass a table name, and a set of column family
specifications (at least one), and, optionally, table configuration.
Column specification can be a simple string (name), or a dictionary
(dictionaries are described below in main help output), necessarily
including NAME attribute.

**Comment by vonkonyoung** [comment]
查看进程，进程正常启动：
[root@hadoop-master bin]# jps
3206 SecondaryNameNode
6374 HMaster
2744 NameNode
7211 ThriftServer
3404 ResourceManager
3790 RunJar
3695 RunJar
6831 HRegionServer
7695 Main
8015 Jps

**Comment by vonkonyoung** [comment]
查看日志：
2021-02-15 18:59:23,710 INFO  [ReadOnlyZKClient-hadoop-master:22181,hadoop-slave1:22181,hadoop-slave2:22181@0x2cc3bd23-SendThread(localhost:22181)] zookeeper.ClientCnxn: O
pening socket connection to server localhost/192.168.1.137:22181. Will not attempt to authenticate using SASL (unknown error)
2021-02-15 18:59:23,712 WARN  [ReadOnlyZKClient-hadoop-master:22181,hadoop-slave1:22181,hadoop-slave2:22181@0x2cc3bd23-SendThread(localhost:22181)] zookeeper.ClientCnxn: S
ession 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: 拒绝连接
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)

2021-02-15 19:00:24,857 INFO  [ReadOnlyZKClient-hadoop-master:22181,hadoop-slave1:22181,hadoop-slave2:22181@0x2cc3bd23-EventThread] zookeeper.ClientCnxn: EventThread shut 
down for session: 0x277a55807560002
2021-02-15 19:00:34,029 WARN  [Thread-14] master.HMaster: hbase:meta,,1.1588230740 is NOT online; state={1588230740 state=OPEN, ts=1613386765237, server=hadoop-slave2,1602
0,1546609011527}; ServerCrashProcedures=true. Master startup cannot progress, in holding-pattern until region onlined; operator intervention required. Schedule an assign.

**Comment by vonkonyoung** [comment]
把zookeeper下的version删掉：
[root@hadoop-slave1 hbase]# ls
bin  CHANGES.md  conf  docs  hbase-webapps  LEGAL  lib  LICENSE.txt  logs  NOTICE.txt  README.txt  RELEASENOTES.md  zookeeper
[root@hadoop-slave1 hbase]# cd zookeeper/
[root@hadoop-slave1 zookeeper]# ls
myid  version-2
[root@hadoop-slave1 zookeeper]# rm -rf version-2/
