### ISSUE TITLE
MetaException

### ISSUE THREAD

**Issue by vonkonyoung** [vonkonyoung/myhbase#2]
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=36, exceptions:
Tue Feb 16 23:31:05 CST 2021, null, java.net.SocketTimeoutException: callTimeout=60000, callDuration=68290: row 'user_profile,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,16020,1613387868265, seqNum=0
Caused by: java.net.SocketTimeoutException: callTimeout=60000, callDuration=68290: row 'user_profile,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,16020,1613387868265, seqNum=0
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:159)
Caused by: java.net.SocketTimeoutException: callTimeout=60000, callDuration=68290: row 'user_profile,,' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,16020,1613387868265, seqNum=0
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:159)
Caused by: java.net.ConnectException: 拒绝连接
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)

**Comment by vonkonyoung** [comment]
原来是因为创建的外部表的原因：
    > user_id STRING comment "userID",
    > information map<string, DOUBLE> comment "user basic information",
    > article_partial map<string, DOUBLE> comment "article partial",
    > env map<string, INT> comment "user env")
    > COMMENT "user profile table"
    > STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
    > WITH SERDEPROPERTIES ("hbase.columns.mapping" = ":key,basic:,partial:,env:")
    > TBLPROPERTIES ("hbase.table.name" = "user_profile");
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. AlreadyExistsException(message:Table user_profile_hbase already exists)
hive> create external table user_profile_hbase(
    > user_id STRING comment "userID",
    > information map<string, DOUBLE> comment "user basic information",
    > article_partial map<string, DOUBLE> comment "article partial",
    > env map<string, INT> comment "user env")
    > COMMENT "user profile table"
    > STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
    > WITH SERDEPROPERTIES ("hbase.columns.mapping" = ":key,basic:,partial:,env:")
    > TBLPROPERTIES ("hbase.table.name" = "abc");
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. MetaException(message:MetaException(message:HBase table abc doesn't exist while the table is declared as an external table.)

去掉外部表关键字就行：
hive> create  table user_profile_hbase1(
    > user_id STRING comment "userID",
    > information map<string, DOUBLE> comment "user basic information",
    > article_partial map<string, DOUBLE> comment "article partial",
    > env map<string, INT> comment "user env")
    > COMMENT "user profile table"
    > STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
    > WITH SERDEPROPERTIES ("hbase.columns.mapping" = ":key,basic:,partial:,env:")
    > TBLPROPERTIES ("hbase.table.name" = "abc");
OK
Time taken: 2.807 seconds
所以why?????
